# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumEditorText',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_text_mediumeditor_mediumeditortext', serialize=False, to='cms.CMSPlugin')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name_plural': 'texts',
                'verbose_name': 'text',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
